### ISSUE TITLE
“收款码合并”能不能支持云闪付的收款码？

### ISSUE THREAD

**Issue by peer2poor** [Ice-Hazymoon/MikuTools#1]
大佬你好，“收款码合并”能不能支持云闪付的收款码？搞个4合一的。

谢谢大佬。

**Comment by Ice-Hazymoon** [comment]
暂时不支持，但是有这个计划，未来会增加以下功能
- 不一定需要上传三张收款码也能合并
- 指定一个平台上传任意一个二维码，而不用做验证
