### ISSUE TITLE
大佬您好，来求教一下新番视频的拉取问题。

### ISSUE THREAD

**Issue by mqdlzh** [Ice-Hazymoon/MikuTools#13]
曾经试过用OneDrive作为视频源来搭建一个视频站，但OneDrive国内访问速度并不理想。今天在逛GitHub有幸看到了这个神奇的在线工具箱，打开访问发现新番里视频播放来源是quan.qq.com（QQ圈子），请问是怎么做到的？能否教一下？谢谢大佬了！

**Comment by Ice-Hazymoon** [comment]
我也是爬取其他一些视频站得到的地址，不知道他的上传接口是什么，可以试试抓一下包，百度贴吧的视频接口貌似挺好抓的，不过限制大小500M
