### ISSUE TITLE
“这是什么动漫”功能上传图片问题

### ISSUE THREAD

**Issue by ohmyga233** [Ice-Hazymoon/MikuTools#14]
上传的图片大小为 788KB 但却提示 “请选择大小在1M以内的图片”。
![](https://i.loli.net/2019/06/22/5d0e4485bf40e25316.png)
![](https://i.loli.net/2019/06/22/5d0e44f271ba490843.gif)

**Comment by Ice-Hazymoon** [comment]
抱歉，由于[https://trace.moe/](https://trace.moe/) 的接口限制，只能上传编码后的图片，编码后会比原图片大百分之30左右，所以实际只能上传6-700kb左右的图片，如有需要可以直接使用 [https://trace.moe/](https://trace.moe/)来查询
