### ISSUE TITLE
Why can't I download the magnetic link search?

### ISSUE THREAD

**Issue by wdpa23a8101** [Ice-Hazymoon/MikuTools#15]
Hello
Why can't I download the magnetic link search?

**Comment by Ice-Hazymoon** [comment]
You can copy the link and use the bittorrent client to download later.

![image](https://user-images.githubusercontent.com/25239977/59971510-04462780-95b0-11e9-9130-2f54f98c5cef.png)
![image](https://user-images.githubusercontent.com/25239977/59971512-10ca8000-95b0-11e9-8497-a682eed74495.png)

**Comment by wdpa23a8101** [comment]
> 您可以复制链接并使用bittorrent客户端稍后下载。
> 
> ![图片](https://user-images.githubusercontent.com/25239977/59971510-04462780-95b0-11e9-9130-2f54f98c5cef.png)
> ![图片](https://user-images.githubusercontent.com/25239977/59971512-10ca8000-95b0-11e9-8497-a682eed74495.png)
Thank you so much.
