### ISSUE TITLE
YouTube 视频下载 报错

### ISSUE THREAD

**Issue by amin168** [Ice-Hazymoon/MikuTools#18]
当点击获取后，报如下错误

`https://www.youtube.com/watch?v=MJH1WVWa3rE`

![1](https://user-images.githubusercontent.com/10808093/60381109-f3028c80-9a81-11e9-8d40-6ef1d27169a0.png)

**Comment by Ice-Hazymoon** [comment]
感谢反馈，会在下个版本修复
