### ISSUE TITLE
V2ray,SS,SSR地址直接复制无法导入

### ISSUE THREAD

**Issue by Remalloc** [Ice-Hazymoon/MikuTools#19]
这几个地址后面都有多余字符，直接复制会导致无法导入
* V2ray:地址后面多了个```</code>```标签
* SS:地址后面多出形如```==<a href="?q=%23%E7%BF%BB%E5%A2%99%E5%85%9A_%E6%97%A5%E6%9C%AC">#xxx</a>-xxx ```
* SSR:后面多了个逗号

**Comment by Ice-Hazymoon** [comment]
感谢反馈，会尽快修复
