### ISSUE TITLE
[Bilibili 视频下载] 视频集下载都是相同的

### ISSUE THREAD

**Issue by icesnaker** [Ice-Hazymoon/MikuTools#2]
作者你好，

视频连接：https://www.bilibili.com/video/av41291982/?p=1

问题描述：
- 将这个视频复制到Miku里后，得到了连接，用Aria2下载 P1(第一集) 都正常
- 但下载P3（第三集）时候Miku给出了和P1一样的连接

不知道是什么原因，是我自己操作问题，还是的确是Miku不能识别这种连续集这种？

**Comment by Ice-Hazymoon** [comment]
这是一个问题，会在以后修复，最近暂时没有时间写

**Comment by Ice-Hazymoon** [comment]
已修复

**Comment by icesnaker** [comment]
谢谢作者
