### ISSUE TITLE
您好，追新番里面的视频看不了啊

### ISSUE THREAD

**Issue by Seagant** [Ice-Hazymoon/MikuTools#20]

**Comment by KeJunMao** [comment]
您好，追新番里面的视频看的了啊

**Comment by Seagant** [comment]
> 您好，追新番里面的视频看的了啊

啊？？？我为什么怎么就是看不了。。。点播放点集数都不好使。。。。

**Comment by Seagant** [comment]
> > 您好，追新番里面的视频看的了啊
> 
> 啊？？？我为什么怎么就是看不了。。。点播放点集数都不好使。。。。

但是我手机就能播放，这。。。是咋回事
