### ISSUE TITLE
我几岁了--距离下次生日结果有问题

### ISSUE THREAD

**Issue by anye1998** [Ice-Hazymoon/MikuTools#23]
![图片](https://user-images.githubusercontent.com/43033792/62003838-9ad9ab80-b14f-11e9-9be2-a6185ba48466.png)
这个虽然没算，但明显不对吧，怎么可能大于一年？？
麻烦大佬查看一下是不是算法问题。

**Comment by KeJunMao** [comment]
晚一点删除该功能

**Comment by Ice-Hazymoon** [comment]
已暂时移除，修复后重新上线，感谢反馈
