### ISSUE TITLE
使用的网络是需要翻Wall么？

### ISSUE THREAD

**Issue by gianozdp** [Ice-Hazymoon/MikuTools#25]
在CN网络环境，未FQ，访问时可以显示首页标题，但是网页里的内容是空白的。不知是不是需要FQ的原因？

**Comment by gianozdp** [comment]
补充一下，我说的是将程序拷贝到本地web服务器再访问的情况。

**Comment by Ice-Hazymoon** [comment]
要将打包好的内容放到 web 服务器根目录，如有其它问题，请提供具体环境配置能参数

**Comment by gianozdp** [comment]
apache 2.4 + nignx + php 7.0
还需要什么其他参数？

**Comment by Ice-Hazymoon** [comment]
截图下web服务器根目录的文件

**Comment by gianozdp** [comment]
[url=http://image-bugs.com/image/H7qM][img]http://image-bugs.com/images/2019/08/05/_20190806084723.jpg[/img][/url]
[url=http://image-bugs.com/image/H7qP][img]http://image-bugs.com/images/2019/08/05/miku.jpg[/img][/url]

**Comment by cnjiaoliu** [comment]
一般你改了源代码就会这样

**Comment by Ice-Hazymoon** [comment]
参考 [https://github.com/Ice-Hazymoon/MikuTools/blob/master/dist.7z](https://github.com/Ice-Hazymoon/MikuTools/blob/master/dist.7z) 的目录配置，如果不会打包直接解压 `dist.7z` 到根目录

**Comment by gianozdp** [comment]
谢谢，放到根目录下解决了。问题，好多小工具没有啊，呵呵。比如最喜欢的视频下载，番号查询的。。。
