### ISSUE TITLE
页面选择随机动漫背景产生的问题

### ISSUE THREAD

**Issue by cnjiaoliu** [Ice-Hazymoon/MikuTools#27]
页面选择随机背景时会调用API：(http://api.btstu.cn/sjbz/?lx=dongman)
但由于API接口是http，部署了全站https的话，会导致被浏览器标识不安全，但我试了一下，API是可以用https的 https://api.btstu.cn/sjbz/?lx=dongman
所以建议把源码改一下（主站也是）

**Comment by cnjiaoliu** [comment]
还有，主站服务器在哪里啊，访问那么慢

**Comment by Ice-Hazymoon** [comment]
已替换成 "//api.btstu.cn/sjbz/?lx=dongman&k="
