### ISSUE TITLE
同步配置上传失败

### ISSUE THREAD

**Issue by artiga033** [Ice-Hazymoon/MikuTools#29]
![tmp](https://user-images.githubusercontent.com/16872488/63093748-eafe9d80-bf98-11e9-9ffc-979cbfbd6fc8.png)

状态码400；响应如下：
`{"msg":"[{\"value\":{\"text\":\"eyJzZXR0aW5nIjp7ImFuaW1hdGlvbnMiOnRydWUsImhpZGUiOltdLCJmYXZvcml0ZXMiOltdLCJoaWRlQ2F0ZWdvcnkiOmZhbHNlLCJoaWRlUGF5IjpmYWxzZSwiaGlkZU5vdGljZSI6ZmFsc2UsImNzcyI6IiIsImpzIjoiIiwiaW5OZXdUYWIiOmZhbHNlLCJiZyI6eyJ0eXBlIjoiYmluZyIsInVwbG9hZCI6eyJ1cmwiOiIiLCJkZWxldGVVcmwiOiIifSwiY3VzdG9tVXJsIjoiIiwiYmx1ciI6MCwib3BhY2l0eSI6NTAsInRyYW5zcGFyZW50RWwiOnRydWV9fSwiZGFyayI6ZmFsc2V9\",\"time\":1565870191},\"msg\":\"Invalid value\",\"param\":\"config\",\"location\":\"body\"}]"}`

**Comment by Ice-Hazymoon** [comment]
已删除该功能
