### ISSUE TITLE
关于bilibili视频解析结果反馈

### ISSUE THREAD

**Issue by hangitfan** [Ice-Hazymoon/MikuTools#30]
真的太感谢作者发布的这个工具集了, 特别解析b站的视频可以把各个清晰度下载地址都直接展示出来
有一个问题想请教下, 过去使用浏览器脚本需要在播放时才能嗅探出来的地址, 我看解析出来域名是acgvideo.com, 而在mikutools里面解析出来的域名是upos-hz-mirrorakam.akamaized.net,  这两个有什么技术上的区别吗? 可以同时在解析结果里展示吗?
多谢 !

**Comment by Ice-Hazymoon** [comment]
视频使用的CDN地址不同吧，应该没有什么区别，建议使用 [哔哩哔哩助手](https://chrome.google.com/webstore/detail/哔哩哔哩助手：bilibilicom-综合辅助扩展/kpbnombpnpcffllnianjibmpadjolanh) 这个Chrome插件，可以解析所有清晰度

**Comment by hangitfan** [comment]
> 视频使用的CDN地址不同吧，应该没有什么区别，建议使用 [哔哩哔哩助手](https://chrome.google.com/webstore/detail/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%8A%A9%E6%89%8B%EF%BC%9Abilibilicom-%E7%BB%BC%E5%90%88%E8%BE%85%E5%8A%A9%E6%89%A9%E5%B1%95/kpbnombpnpcffllnianjibmpadjolanh) 这个Chrome插件，可以解析所有清晰度

助手插件有试用过, 但是用的时候有一个问题就是只能解析当前播放视的下载地址? 这种个人感觉不友好, 因为还得登录账号然后再打开页面...
至于域名, 我试过在播放页调试加载的地址是acgvideo.com, 这个域名自己有cdn, 然后下载速度比另外一个域名爆炸得多, 所以想问问能不能在工具里解析到这个地址.....
