### ISSUE TITLE
How to Add New Tools  -  如何添加新工具

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [Ice-Hazymoon/MikuTools#40]
I want to know the basic steps to Add new tools. I want to add this tool how could I add this 

我想知道添加新工具的基本步骤。我想添加此工具，我该如何添加它 (https://www.npmjs.com/package/twitter-video-downloader)

我不懂中文，但我尝试使用翻译

**Comment by rahulkumarsingh73690** [comment]
Please Help Me I need to Learn How to Add New Dynamic Tools.  If you don't have time then please at least provide 1 script (youtube video downloader / twitter video downloader)

@KeJunMao

**Comment by rahulkumarsingh73690** [comment]
> Please Help Me I need to Learn How to Add New Dynamic Tools. If you don't have time then please at least provide 1 script (youtube video downloader / twitter video downloader)
> 
> @KeJunMao

I will check code and try to make similar

**Comment by sunjie666** [comment]
The author is Chinese, please try to use Chinese
你懂中文请直接用中文提问，谢谢

**Comment by rahulkumarsingh73690** [comment]
请帮我，我需要学习如何在Mikutools中添加新的动态工具。如果您没有时间，请至少提供1个脚本（youtube视频下载器，Facebook视频下载器，twitter视频下载器）

我知道https://www.npmjs.com中提供的这些类型的脚本

@Ice-Hazymoon

**Comment by Ice-Hazymoon** [comment]
Sorry, some features require server support, so there is no open source for the time being. If you need to add tools, you can refer to the code in pages/*.vue. If you don't understand Chinese, you may not be able to continue development, but we are gradually improving the documentation.

English is not my native language, I hope you can understand it.

**Comment by rahulkumarsingh73690** [comment]
> Sorry, some features require server support, so there is no open source for the time being. If you need to add tools, you can refer to the code in pages/*.vue. If you don't understand Chinese, you may not be able to continue development, but we are gradually improving the documentation.
> 
> English is not my native language, I hope you can understand it.

Thanks For Replying

I know these things require server setup that's why I am asking you, for example, how can I set it up (https://www.npmjs.com/package/youtube-dl).

I added in ytdl in package.json but i want to know how to set up in pages/.vue file for this.

**Comment by KeJunMao** [comment]
购买一个云服务器，编写服务端api，使用 axios请求。

> 感谢您对本项目的支持，有关后端的问题请不要再重新打开 issue 了！谢谢。

**Comment by rahulkumarsingh73690** [comment]
> 感谢您对本项目的支持，有关后端的问题请不要再重新打开 issues 了！谢谢。

Thanks :)
