### ISSUE TITLE
免编译压缩包404

### ISSUE THREAD

**Issue by sunjie666** [Ice-Hazymoon/MikuTools#42]
你在md文件说的免编译压缩包 dist.zip 
访问提示 404: Not Found

**Comment by RikkaBlue** [comment]
https://github.com/Ice-Hazymoon/MikuTools/blob/73f38fcd72fe737690356d1bd12807c595e9922f/dist.zip 
可在此处下载

**Comment by Ice-Hazymoon** [comment]
已更新README

**Comment by KeJunMao** [comment]
请阅读 wiki https://github.com/Ice-Hazymoon/MikuTools/wiki/%E9%9D%9E%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8C%97
