### ISSUE TITLE
“帮你百度”工具错误

### ISSUE THREAD

**Issue by LiziMu2333** [Ice-Hazymoon/MikuTools#66]
生成出来的页面，输入框悬浮后的层级覆盖了鼠标
http://recordit.co/kCSQBhWjA1
![kCSQBhWjA1](https://user-images.githubusercontent.com/7465727/86575638-30113100-bfaa-11ea-8724-0f1b34b1e9e6.gif)

**Comment by KeJunMao** [comment]
开源版无异常，请使用站内留言反馈
