### ISSUE TITLE
【咨询】知乎免登录的实现原理

### ISSUE THREAD

**Issue by LiXin-x** [Ice-Hazymoon/MikuTools#7]
希望能够简单描述一下「知乎免登录」的实现原理。

目前大概知道是先到服务器做一次跳转，可是之后的流程就看不懂了。之后直接请求知乎问题的路径，请求参数略有不同，并且带上一定的搜索引擎参数？猜不下去了。

我是真迷糊了，新手一枚，希望作者能简单说明一下原理。

**Comment by Ice-Hazymoon** [comment]
跳转到知乎的时候，只要referer里包含一些相关的参数就可以免登陆查看回答了
![image](https://user-images.githubusercontent.com/25239977/57935232-f12aa280-78f3-11e9-96c4-b6757cad5d77.png)

**Comment by LiXin-x** [comment]
感谢前辈，
我昨天也看到这个请求参数了，但还是受限于自己 HTTP 协议知识的薄弱，补一下知识。
再次感谢作者抽空回答 🙏🤗

**Comment by LiXin-x** [comment]
感谢前辈，
我昨天也看到这个请求参数了，但还是受限于自己 HTTP 协议知识的薄弱，补一下知识。
再次感谢作者抽空回答 🙏🤗

**Comment by shensuv** [comment]
貌似这个方法这段时间已经失效了。
