### ISSUE TITLE
在线上部署后访问各工具都会重定向问题

### ISSUE THREAD

**Issue by 188** [Ice-Hazymoon/MikuTools#75]
![mk](https://user-images.githubusercontent.com/3905303/126807482-d7302cb2-34e0-43ca-933b-672e904a2fd6.jpg)
如图所示，每次刷新也是这样
比如刷新：https://a.com/lifecount
会先转到 https://a.com/lifecount/
然后再转到 https://a.com/lifecount

请问一下这个配置下能解决问题

**Comment by 188** [comment]
![mk](https://user-images.githubusercontent.com/3905303/126807845-1b873d34-4cca-4c60-b54f-f5d759e6fc4a.jpg)

**Comment by Ice-Hazymoon** [comment]
把 pwa 关了试试 https://github.com/Ice-Hazymoon/MikuTools/blob/56395e307451125ae712256d838a36bf9e514b82/nuxt.config.js#L167

**Comment by 188** [comment]
关了也不行，还是一样的问题

**Comment by 188** [comment]
![mk](https://user-images.githubusercontent.com/3905303/126862665-e8e92b78-6048-4dc5-89aa-29dec9667a9c.jpg)
还是有这个问题，只是在首页那边的没有了，在刷新或打开一个子页面时会存在这个问题？
现在是 pwa 关闭状态

**Comment by Ice-Hazymoon** [comment]
不影响使用吧

**Comment by 188** [comment]
是不影响使用，这个是什么原因引起的，能优化吗？

**Comment by Ice-Hazymoon** [comment]
参考：

https://webmasters.stackexchange.com/questions/35643/is-trailing-slash-automagically-added-on-click-of-home-page-url-in-browser/35646

https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#trailingslash

**Comment by 188** [comment]
非常感谢上面的方法能解决这个问题，谢谢。
但是还是想不带后面的/ 又不想有301，打包发布到线上后还是不行
我看nuxt官方文档上面 router.trailingSlash=false 时是不加/ 的
实际上设置false时还是加上了，这个有什么办法解决吗？

**Comment by Ice-Hazymoon** [comment]
我没弄过这个需求，所以暂时不知道具体的解决方案，也对这部分不是很了解

请求 `/lifecount/` 时，请求的具体内容是 `/lifecount/index.html`，如果末尾不加 `/`，访问的就是 `lifecount` 这个文件，我觉得应该是 http 服务器的特性

在新版本的 nginx（≥1.11.8） 中，可以通过设置 absolute_redirect off; 来解决

```
server {
    listen       8080;
    server_name  www.mydomain.com;
     
    absolute_redirect off;    #取消绝对路径的重定向
     
    root   html;
    ...
}
```

我也没试过这个方案，你可以尝试一下

**Comment by 188** [comment]
我尝试了 absolute_redirect off; 
router.trailingSlash=false 、 router.trailingSlash=true  、和不加这个配置
都还是不行，但在本地yarn dev 运行时  router.trailingSlash=false  是可以的
这个也很奇怪，感觉不是nginx这的问题，因为我输入 /lifecount/index.html时是打不开的，也就是走的应该是vue路由吧

**Comment by 188** [comment]
我刚在本地测试了一下
用例1：
yarn dev 运行起来后，用nginx反向代理到 http://localhost:3000 一切正常
用例2：
yarn generate 打包后，用nginx指向本地目录 dist ，不管nginx怎么配置都城要301
