### ISSUE TITLE
怎么优化页面大小

### ISSUE THREAD

**Issue by 188** [Ice-Hazymoon/MikuTools#76]
用yarn generate 生成后，线个HTML页面中都会生成大量CSS 和 js脚本，这部分能优化掉吗？
我看你的主站就没有这部分内容
如：
![m1](https://user-images.githubusercontent.com/3905303/126864675-cacf7a10-62c3-40bc-b0ec-c1211213631e.jpg)
![m2](https://user-images.githubusercontent.com/3905303/126864680-94d8e44b-bf2d-4a15-a252-729b0f5df8d0.jpg)

**Comment by Ice-Hazymoon** [comment]
https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-ssr#:~:text=You%20can%20set%20this%20option%20to%20false%20when%20you%20want%20only%20client%20side%20rendering
