### ISSUE TITLE
页面加载速度慢

### ISSUE THREAD

**Issue by wz930206** [Ice-Hazymoon/MikuTools#78]
你好，部署到服务器上之后，请求页面要几十秒。本地启动项目之后，如果刷新页面也需要十几秒的时间才会更新页面，请问这方面你是怎么优化的吗
![image](https://user-images.githubusercontent.com/37261842/140680541-e70ec2df-f016-452b-871a-80d8e5664088.png)

**Comment by KeJunMao** [comment]
这个项目是静态化的，全站cdn试试～
