### ISSUE TITLE
页面加载两次

### ISSUE THREAD

**Issue by 188** [Ice-Hazymoon/MikuTools#80]
又发现一个问题，每次打开页面加载两次，且两次加载都耗时也都在客户端下载了内容，这样的问题怎么解决呀，如下图所示：
整体加载情况：
![image](https://user-images.githubusercontent.com/3905303/141247932-df200642-3090-40e6-8358-851522fa2a9e.png)
第一个加截，正常返回html内容：
![image](https://user-images.githubusercontent.com/3905303/141248070-f8531e04-f0e1-4958-9c54-6293db715d3d.png)
第二个加载，返回内容为空：
![image](https://user-images.githubusercontent.com/3905303/141248149-14456b60-8982-47cf-b49e-1de423fa204d.png)

**Comment by 188** [comment]
找到原因了，自定义背景图那有问题
我没有修改，只是去掉了， 就不提交代码
有时间你来处理一下吧

**Comment by guyuxiu** [comment]
> 

你好，自定义背景图，哪里优化？
