### ISSUE TITLE
有没有打算开发一个 json 格式化的呢

### ISSUE THREAD

**Issue by stevenling** [Ice-Hazymoon/MikuTools#82]
大概这样，这是我写的。
![image](https://user-images.githubusercontent.com/19485239/173769989-98780784-82aa-4ab7-a1e8-82d9bd865930.png)

**Comment by Ice-Hazymoon** [comment]
已经有了，https://tools.miku.ac/json_editor

**Comment by Ice-Hazymoon** [comment]
如果希望在开源版本中添加，可以提交pr
