### ISSUE TITLE
“帮你百度”功能无法处理空格等字符

### ISSUE THREAD

**Issue by HairlessVillager** [Ice-Hazymoon/MikuTools#85]
我在“帮你百度”的页面输入`C++ 形参重定义`，点击生成的链接后，“百度搜索框”里只有`C++`，跳转到的百度搜索页面只有`C`的搜索结果。

- 操作系统：`Windows 10 (64位)`
- 使用的浏览器及版本：`Edge 105.0.1343.42 (正式版本) (64 位)`

上文提到的链接：https://tools.miku.ac/o/search_help?q=YmFpZHUgQysrIOW9ouWPgumHjeWumuS5iQ

**Comment by KeJunMao** [comment]
开源版本已修复～

**Comment by Ice-Hazymoon** [comment]
已修复 https://tools.miku.ac/o/search_help?q=YmFpZHUgQysrIOW9ouWPgumHjeWumuS5iQ
