### ISSUE TITLE
1000011236 (900×1089)

### ISSUE THREAD

**Issue by ychmun** [Ice-Hazymoon/MikuTools#88]
> ![constitution-es-large.jpg](https://user-images.githubusercontent.com/94536439/211881285-ce7dfa8c-fd3c-4693-995e-2da88e978a55.jpg![share-1673453484128.png](https://user-images.githubusercontent.com/94536439/211881369-3634440c-48ac-4f19-8152-8cc7087b2e36# .png)~~~~)

**Comment by KeJunMao** [comment]
?
