### ISSUE TITLE
一个小小的建议

### ISSUE THREAD

**Issue by bougieL** [Ice-Hazymoon/MikuTools#9]
感觉搜索可以做的更智能点，例如输入 `duanlian` 或 `dl` 可以直接搜索断链生成，可以做成类似 Mac 聚焦搜索或者类似 Alfred 那样 :thinking:

**Comment by Ice-Hazymoon** [comment]
这么搞的话就只能把所有标题添加一份拼音了，感觉有点麻烦，又不想借助后端实现，所以暂时不会做

**Comment by bougieL** [comment]
有一些库可以做这个，可能搞得 bundle size 比较大

**Comment by Ice-Hazymoon** [comment]
搜索的话其实还好，如果是自动转换成拼音的话，估计光拼音的字典文件就有好几M了，而且前端处理字典性能会很弱

**Comment by bougieL** [comment]
参考 https://hotoo.github.io/pinyin/examples/ ， 这个常用字 gzip 后的 bundle 也就 20k

**Comment by bougieL** [comment]
觉得可以的话我周末提个 pr ？

**Comment by Ice-Hazymoon** [comment]
我那个汉字转拼音的功能就是用的这个库，尝试过在前端使用，但虽说是常用字，还是很多都没覆盖到，所以就直接后端处理了，完整的字典文件有2m左右，处理起来很麻烦

**Comment by Ice-Hazymoon** [comment]
可以提一个看看，如果性能不错的话会合并的

**Comment by bougieL** [comment]
see #11
