### ISSUE TITLE
资源好像加载不上了，尝试过翻墙，但是还是打不开。

### ISSUE THREAD

**Issue by DeSireFire** [Ice-Hazymoon/MikuTools#97]
![image](https://github.com/user-attachments/assets/3679efd7-0970-4572-b0ac-81dd88f1fe04)
![image](https://github.com/user-attachments/assets/11c283b6-c288-4048-a239-fadf41db7d1c)

**Comment by KeJunMao** [comment]
![image](https://github.com/user-attachments/assets/2b4156f5-c697-4380-8ee6-22c1bb80a1bf)

**Comment by DeSireFire** [comment]
> ![image](https://private-user-images.githubusercontent.com/18414281/353680946-2b4156f5-c697-4380-8ee6-22c1bb80a1bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDQ2NjgsIm5iZiI6MTcyMjQwNDM2OCwicGF0aCI6Ii8xODQxNDI4MS8zNTM2ODA5NDYtMmI0MTU2ZjUtYzY5Ny00MzgwLThlZTYtMjJjMWJiODBhMWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA1MzkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MjJiOGVlMTAzYTE4YmJjYzBlNjQzYTI1YzRhZmNmYTM2NzczNjc5MjMxOTU1OGYwYmE5YjU2ZWFlZmZmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfq8tIBkG2LsdpqB3VIMeYiIZ47tqBsZZr_SML7vgss)

在昨天之前，一直都是正常访问的。今天发现不能能访问的时候，才使用代理来尝试。
另外，关于图中的设置，我尝试了，也不行。
![image](https://github.com/user-attachments/assets/7b30ecb8-8bda-4f97-a0ce-1c052b28f020)
![image](https://github.com/user-attachments/assets/f3e6f07e-3bb2-43b3-a06f-4ec38cae29db)

更换浏览器edge,也是打不开；
远程到另一个省份的电脑，也打不开。

**Comment by Ice-Hazymoon** [comment]
修复了

RaXianch ***@***.***> 于 2024年7月31日周三 14:46写道：
